### ISSUE TITLE
django.db.utils.ProgrammingError: column "is_long_token" of relation "django_rest_passwordreset_resetpasswordtoken" does not exist

### ISSUE THREAD

**Issue by kumar-student** [anexia-it/django-rest-passwordreset#142]
Unable to run migrate command

python manage.py makemigrations generated fallowing output

Migrations for 'django_rest_passwordreset':
  /home/user/Desktop/poll_app/venv/lib/python3.8/site-packages/django_rest_passwordreset/migrations/0008_auto_20210808_0449.py
    - Remove field expired from resetpasswordtoken
    - Remove field is_long_token from resetpasswordtoken
    - Remove field used from resetpasswordtoken
Migrations for 'poll_app':
  poll_app/migrations/0017_auto_20210808_0449.py
    - Alter field user on companyprofile

Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, django_rest_passwordreset, polls_app, sessions, sites, socialaccount
Running migrations:
  Applying django_rest_passwordreset.0008_auto_20210808_0449...Traceback (most recent call last):
  File "/home/user/Desktop/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "is_long_token" of relation "django_rest_passwordreset_resetpasswordtoken" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/Desktop/polls_app/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/Desktop/polls_app/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/Desktop/polls_app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 178, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 517, in remove_field
    self.execute(sql)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/Dev/polls_app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "is_long_token" of relation "django_rest_passwordreset_resetpasswordtoken" does not exist

**Comment by nezhar** [comment]
The module has currently 3 migrations: https://github.com/anexia-it/django-rest-passwordreset/tree/master/django_rest_passwordreset/migrations

Do you use a fork of the module?
